#!/bin/bash

sudo -v # ask for password only at the beginning

brew update
brew upgrade

brew install bash
echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/bash

brew install git
brew tap caskroom/cask
brew install node
brew install ondir
brew install hub
brew install ccat
brew install ngrok
brew install diff-so-fancy

# brew cask install caskroom/versions/sublime-text3
# brew cask install webstorm
brew cask install iterm2
brew cask install visual-studio-code
# brew cask install mou
# brew cask install genymotion

brew cask install google-chrome
brew cask install firefox
brew cask install opera

brew cask install insomnia
brew cask install skype
brew cask install keka
brew cask install imageoptim
brew cask install vlc
brew cask install franz
brew cask install spotify

brew install git-lfs

brew cleanup
